// SHOW
export const GET_SHOW_REQUESTED = "GET_SHOW_REQUESTED";
export const GET_SHOW_SUCCESS = "GET_SHOW_SUCCESS";
export const GET_SHOW_FAILED = "GET_SHOW_FAILED";

//DETAILS
export const GET_DETAILS_REQUESTED = "GET_DETAILS_REQUESTED";
export const GET_DETAILS_SUCCESS = "GET_DETAILS_SUCCESS";
export const GET_DETAILS_FAILED = "GET_DETAILS_FAILED";